version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=3048M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1111'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: '1111'
      MYSQL_DATABASE: 'magento-clean'
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    links:
      - elasticsearch
      - redis
    security_opt:
      - seccomp:unconfined

  redis:
      image: redis:latest
      container_name: redis
      restart: always
      ports: 
        - 6379:6379
      volumes:
        - redisdata:/data

  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  php:
    image: php:7.4-apache
    container_name: php
    build: .
    volumes: 
      - /var/www/html:/var/www/html
    ports:
      - 80:80

volumes:
  redisdata:
